### ISSUE TITLE
Set command: Add 'readback', remove 'wait' param

### ISSUE THREAD

**Issue by kasemir** [PythonScanClient/PyScanClient#2]
Set command needs a way to configure the 'readback' as different from the primary device name.
When doing that, the 'wait' can be made implicit, see https://github.com/kasemir/ScanClientSandbox/blob/master/scan_client/scan/commands/set.py and https://github.com/kasemir/ScanClientSandbox/blob/master/scan_client/test_commands.py

**Comment by ksdj** [comment]
I see.You code means that there is a implicit relation among 'timeout' ,'tolerance' and 'readback'.
Should this relation also suitable for command 'Loop'?

**Comment by kasemir** [comment]
Yes. On the client side, when setting the 'readback', that results in enabling the <wait> for that <readback> to match the desired value within the <tolerance>.
The <timeout> applies to both the callback completion and the read back check.

For convenience, on the client side I would allow this for the read back parameter:

False means read back is not used.
True means wait-for-readback is enabled, using the primary pv name.
"SomePvName" means readback uses that pv name, not the primary pv name.


Yes, the loop command is the same in this regard.
