### ISSUE TITLE
Use lower-case filenames

### ISSUE THREAD

**Issue by kasemir** [PythonScanClient/PyScanClient#4]
From the Style Guide for Python Code, https://www.python.org/dev/peps/pep-0008: "Modules should have short, all-lowercase names. Underscores can be used in the module name if it improves readability."

-> Rename all the files

**Comment by ksdj** [comment]
I've changed most of modules.
But what about:
Set.py  
Log.py
-- These 2 command conflicts with a lot of sys libs and 3rd party libs
Command.py  --conflicts with distutils.command
Include.py  --conflicts with xml.etree.ElementInclude
This part really a tricky one.

--Naming is such a difficult work because It's art other than tech.

**Comment by kasemir** [comment]
The commands keep their name, the module file name changes:
set.py defines `Set`, include.py defines `Include`.

There's no change in the command names, so no new conflict.

**Comment by kasemir** [comment]
Sorry, we misunderstood.
The class names should remain as they are: ScanClient, Set, Command, Loop, ...

The file names should be lowercase as per the Style Guide for Python Code: scan/client/scan_client.py,  set.py, command.py, loop.py.

**Comment by kasemir** [comment]
Your last commit left the file names in contradiction to the Style Guide for Python Code: ScanClient.py, but changed the class name which didn't need to be changed.

**Comment by kasemir** [comment]
Also,  scan/commands/CmdSequence.py was removed. Looks like you wanted to add  scan/commands/cmd_seq.py, but that was never added.
Overall, that commit may best be reverted.

**Comment by ksdj** [comment]
Yes, when I rename the System seems not case sensitive.
I'm reverting now.

**Comment by kasemir** [comment]
Right. Linux is the only OS where the file names tend to be case sensitive, depending on the file system. That's why the Style Guide for Python Code recommends lower case only for the file names.
