### ISSUE TITLE
Update ScanClient to use urllib2

### ISSUE THREAD

**Issue by kasemir** [PythonScanClient/PyScanClient#5]
.. because 'requests' library is not a core python lib.

Using urllib2 may be a little less convenient, but it's a core python lib that works out of the box with both jython and python.

**Comment by kasemir** [comment]
May not be less convenient at all, see http://rest.elkstein.org/2008/02/using-rest-in-python.html

**Comment by ksdj** [comment]
OK, I will change 'requests' to 'urllib2'.

**Comment by kasemir** [comment]
Thanks, I see progress towards that in `ScanClient`. When done, there should be no more "import requests" or "from requests import status_code" since that fails under jython.

**Comment by shengb** [comment]
I cleaned up the code, and removed the dependency on requests lib.

**Comment by kasemir** [comment]
Thank you, Guabao!
Are you done?
I'd like to update the client to include it in the documentation.
