### ISSUE TITLE
ScanClient connection close() and exception handling

### ISSUE THREAD

**Issue by kasemir** [PythonScanClient/PyScanClient#8]
ScanClient has a few sections like this:
```
try:
   conn = urllib2.urlopen
   .. do_something ..
   conn.close()
except Exception as ex:
            raise ex
```

It's great to think about closing the connection, and also to handle exceptions.
In this example, however, `except` simply raises the original exception, it doesn't add anything.
If `.. do_something ..` fails, `close()` is not called. 

Better:
```
conn = urllib2.urlopen
try:
   .. do_something ..
finally:
   conn.close()
```

**Comment by ksdj** [comment]
Ah! Yes it is! I will change this.
